"""Shared Pydantic schemas and user prompt helper.

System prompts are now generated by ``harness.ContextBuilder`` from the
unified ``ToolRegistry`` so the model always sees the exact tool vocabulary
and approval rules that are configured in code.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class PlannerAction(BaseModel):
    """One action the LLM wants the FarmBot to perform."""

    kind: str = Field(..., description="Action kind, e.g. 'move', 'water'.")
    params: dict[str, Any] = Field(
        default_factory=dict, description="Action parameters, kind-specific."
    )


class PlannerResponse(BaseModel):
    """Top-level shape the LLM must return."""

    actions: list[PlannerAction] = Field(
        default_factory=list,
        description="Ordered list of actions to execute, in order.",
    )
    rationale: str = Field(
        default="", description="One-sentence explanation of the plan."
    )


def build_user_prompt(
    request: str,
    *,
    world_context: str | None = None,
) -> str:
    parts: list[str] = []
    if world_context:
        parts.append("Current world model:\n" + world_context)
    parts.append(f"Request: {request}")
    return "\n\n".join(parts)
