"""Backend abstraction for robot hardware.

All action handlers talk to a ``RobotBackend`` implementation through
``watering_service.get_backend()``. This keeps the API server decoupled
from serial details and lets us swap in a simulator or a different board
later without touching handlers.
"""

from __future__ import annotations

from typing import Any, Protocol


class RobotBackend(Protocol):
    """The surface area the action handlers need from any robot backend."""

    def connect(self) -> None: ...
    def get_status(self) -> dict[str, Any]: ...
    def move(self, x: float, y: float, z: float, speed: float | None = None) -> None: ...
    def find_home(self, axis: str = "all", speed: float = 100) -> None: ...
    def set_home(self, axis: str = "all") -> None: ...
    def read_pin(self, pin: int, mode: str = "digital") -> Any: ...
    def write_pin(
        self,
        pin: int,
        value: int,
        mode: str = "digital",
        seconds: float | None = None,
    ) -> None: ...
    def control_peripheral(
        self, peripheral_name: str, value: int, mode: str | None = None
    ) -> None: ...
    def water(self, seconds: float) -> None: ...
    def e_stop(self) -> None: ...
    def take_photo(self) -> None: ...
    def get_images(
        self, limit: int = 10, *, refresh: bool = False
    ) -> list[dict[str, Any]]: ...
    def get_xyz(self) -> Any: ...
    def refresh_xyz(self) -> Any: ...
    def get_last_messages(self) -> Any: ...
    def send_message(
        self,
        message: str,
        message_type: str = "info",
        channels: list[str] | None = None,
    ) -> None: ...
    def toast(self, message: str, message_type: str = "info") -> None: ...
    def mount_tool(self, tool_name: str) -> None: ...
    def dismount_tool(self) -> None: ...
    def reboot(self) -> None: ...
    def measure_soil_height(self) -> Any: ...


__all__ = ["RobotBackend"]
